use_frameworks!

platform :ios, '8.0'

target 'YHRunLoopTask_Example' do
  pod 'YHRunLoopTask', :path => '../'

  target 'YHRunLoopTask_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
